DELIMITER //
CREATE PROCEDURE displaySupplierRatings()
BEGIN
DROP TEMPORARY TABLE IF EXISTS TEMP_TABLE;
CREATE TEMPORARY TABLE TEMP_TABLE (
    SUPP_ID INT(5),
    STARS DECIMAL(10,2)
    );

INSERT INTO TEMP_TABLE(
SELECT SP.SUPP_ID,AVG(R.STARS) STARS
FROM ORDERS O,RATING R,SUPPLIER_PRICING SP
WHERE O.ORD_ID=R.ORD_ID
AND O.PRICING_ID = SP.PRICING_ID
GROUP BY SP.SUPP_ID);
SELECT S.SUPP_ID , S.SUPP_NAME,T.STARS,
(CASE WHEN T.STARS = 5 THEN 'Excellent Service'
WHEN T.STARS >4 THEN 'Good Service'
 WHEN T.STARS >2 THEN 'Average Service'
ELSE 'Poor Service'
END) Type_Of_Service
FROM SUPPLIER S,TEMP_TABLE T
WHERE S.SUPP_ID = T.SUPP_ID;END //